### ISSUE TITLE
slice index starts at 312 but ends at 305

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#50]
@trgill is seeing this and I am too. I'm not sure when it started.
```
thread 'real_test_linear_device' panicked at 'slice index starts at 312 but ends at 305', src/libcore/slice.rs:584

10: <core::ops::Range<usize> as core::slice::SliceIndex<T>>::index
             at /builddir/build/BUILD/rustc-1.17.0-src/src/libcore/slice.rs:707
  11: core::slice::<impl core::ops::Index<I> for [T]>::index
             at /builddir/build/BUILD/rustc-1.17.0-src/src/libcore/slice.rs:560
  12: <collections::vec::Vec<T> as core::ops::Index<core::ops::Range<usize>>>::index
             at /builddir/build/BUILD/rustc-1.17.0-src/src/libcollections/vec.rs:1442
  13: devicemapper::dm::DM::do_ioctl
             at /home/agrover/git/stratis/devicemapper-rs/src/dm.rs:152
  14: devicemapper::dm::DM::device_create
             at /home/agrover/git/stratis/devicemapper-rs/src/dm.rs:253
  15: devicemapper::lineardev::LinearDev::new
             at /home/agrover/git/stratis/devicemapper-rs/src/lineardev.rs:37
  16: real_tests::util::simple_tests::test_linear_device
             at ./tests/util/simple_tests.rs:131
```

**Comment by agrover** [comment]
I'm worried this might be due to Undefined Behavior (UB) in `do_ioctl`, especially the unsafe blocks. Very reproducible, so that's good.

**Comment by agrover** [comment]
Good news! It's a kernel issue. See https://www.spinics.net/lists/stable/msg170390.html. `do_ioctl` was assuming hdr.data_size is always >= hdr.data_start, and that's no longer the case in kernels 4.12+ (also backported to previous stable kernel branches).
